app = "binance-p2p-eur-proxy-fra"   # cambialo si ese nombre ya existe
primary_region = "fra"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_stop_machines = true
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
